/**
 * Fourier Series Fitter
 * Fits Fourier series to calibration data for firmware export
 *
 * Uses least squares fitting to find coefficients for:
 * f(θ) = a0 + Σ(ak*cos(kθ) + bk*sin(kθ))
 */

class FourierFitter {
    /**
     * Fit Fourier series to data points
     * @param {Array} points - Array of {angle, value} objects (angle in degrees)
     * @param {number} harmonics - Number of harmonics to fit (1 = a0,a1,b1; 2 = a0,a1,b1,a2,b2; etc.)
     * @param {boolean} periodic - If true, treats data as periodic (0-360°)
     * @returns {Array} Coefficients [a0, a1, b1, a2, b2, ...]
     */
    static fit(points, harmonics, periodic = true) {
        if (points.length === 0) {
            return new Array(1 + 2 * harmonics).fill(0);
        }

        const n = points.length;
        const numCoeffs = 1 + 2 * harmonics;  // a0 + (ak, bk) for each harmonic

        // Build the design matrix A and target vector b
        // We're solving A * x = b for x (the coefficients)
        const A = [];
        const b = [];

        for (const point of points) {
            const theta = point.angle * Math.PI / 180;  // Convert to radians
            const row = [1];  // a0 term

            for (let k = 1; k <= harmonics; k++) {
                row.push(Math.cos(k * theta));  // ak term
                row.push(Math.sin(k * theta));  // bk term
            }

            A.push(row);
            b.push(point.value);
        }

        // Solve using normal equations: (A^T * A) * x = A^T * b
        // This is a simple least squares solution
        const ATA = this.matrixMultiply(this.transpose(A), A);
        const ATb = this.matrixVectorMultiply(this.transpose(A), b);

        // Solve the system using Gaussian elimination
        const coeffs = this.solveLinearSystem(ATA, ATb);

        return coeffs;
    }

    /**
     * Fit calibration sweep data to Fourier series
     * @param {Array} sweepData - Array of {angle, errorX, errorY, errorZ} or {c/b, errorX, errorY, errorZ}
     * @param {string} angleKey - Key to use for angle ('angle', 'c', or 'b')
     * @param {number} harmonics - Number of harmonics
     * @returns {Object} {x: [...coeffs], y: [...coeffs], z: [...coeffs]}
     */
    static fitSweep(sweepData, angleKey, harmonics) {
        // Extract points for each axis
        const xPoints = sweepData.map(p => ({ angle: p[angleKey], value: p.errorX }));
        const yPoints = sweepData.map(p => ({ angle: p[angleKey], value: p.errorY }));
        const zPoints = sweepData.map(p => ({ angle: p[angleKey], value: p.errorZ }));

        return {
            x: this.fit(xPoints, harmonics),
            y: this.fit(yPoints, harmonics),
            z: this.fit(zPoints, harmonics)
        };
    }

    /**
     * Evaluate Fourier series at a given angle
     * @param {Array} coeffs - Coefficients [a0, a1, b1, a2, b2, ...]
     * @param {number} angleDeg - Angle in degrees
     * @returns {number} Evaluated value
     */
    static evaluate(coeffs, angleDeg) {
        const theta = angleDeg * Math.PI / 180;
        let result = coeffs[0];  // a0

        const harmonics = (coeffs.length - 1) / 2;
        for (let k = 1; k <= harmonics; k++) {
            const ak = coeffs[1 + 2 * (k - 1)];
            const bk = coeffs[2 + 2 * (k - 1)];
            result += ak * Math.cos(k * theta) + bk * Math.sin(k * theta);
        }

        return result;
    }

    /**
     * Generate M667 commands for firmware
     * @param {Object} cSweepCoeffs - {x: [...], y: [...], z: [...]} for C sweep
     * @param {Object} bSweepCoeffs - {x: [...], y: [...], z: [...]} for B sweep
     * @returns {string} M667 commands as string
     */
    static generateM667Commands(cSweepCoeffs, bSweepCoeffs) {
        const lines = [];

        lines.push('; Rep5x Calibration Coefficients');
        lines.push('; Generated by Rep5x Calibrator');
        lines.push('; Copy and paste these commands to your printer');
        lines.push('');
        lines.push('; Enable calibration correction');
        lines.push('M667 S1');
        lines.push('');

        // C-sweep coefficients (A, B, C for X, Y, Z)
        lines.push('; C-sweep coefficients (7 per axis: a0, a1, b1, a2, b2, a3, b3)');
        lines.push(`M667 A${this.formatCoeffs(cSweepCoeffs.x)}`);
        lines.push(`M667 B${this.formatCoeffs(cSweepCoeffs.y)}`);
        lines.push(`M667 C${this.formatCoeffs(cSweepCoeffs.z)}`);
        lines.push('');

        // B-sweep coefficients (D, E, F for X, Y, Z)
        lines.push('; B-sweep coefficients (5 per axis: c0, c1, s1, c2, s2)');
        lines.push(`M667 D${this.formatCoeffs(bSweepCoeffs.x)}`);
        lines.push(`M667 E${this.formatCoeffs(bSweepCoeffs.y)}`);
        lines.push(`M667 F${this.formatCoeffs(bSweepCoeffs.z)}`);
        lines.push('');

        lines.push('; Save to EEPROM (optional)');
        lines.push('; M500');

        return lines.join('\n');
    }

    /**
     * Format coefficients as colon-separated string
     */
    static formatCoeffs(coeffs) {
        return coeffs.map(c => c.toFixed(4)).join(':');
    }

    /**
     * Parse M667 response to extract coefficients
     * @param {string} response - Full M667 response from printer
     * @returns {Object} {cSweep: {x, y, z}, bSweep: {x, y, z}} or null if parsing fails
     */
    static parseM667Response(response) {
        const result = {
            cSweep: { x: null, y: null, z: null },
            bSweep: { x: null, y: null, z: null }
        };

        const lines = response.split('\n');
        for (const line of lines) {
            const trimmed = line.trim();

            // Parse C-sweep lines: "C-sweep X: 0.00 0.00 0.00 ..."
            if (trimmed.startsWith('C-sweep X:')) {
                result.cSweep.x = this.parseCoeffLine(trimmed.substring(10));
            } else if (trimmed.startsWith('C-sweep Y:')) {
                result.cSweep.y = this.parseCoeffLine(trimmed.substring(10));
            } else if (trimmed.startsWith('C-sweep Z:')) {
                result.cSweep.z = this.parseCoeffLine(trimmed.substring(10));
            }
            // Parse B-sweep lines
            else if (trimmed.startsWith('B-sweep X:')) {
                result.bSweep.x = this.parseCoeffLine(trimmed.substring(10));
            } else if (trimmed.startsWith('B-sweep Y:')) {
                result.bSweep.y = this.parseCoeffLine(trimmed.substring(10));
            } else if (trimmed.startsWith('B-sweep Z:')) {
                result.bSweep.z = this.parseCoeffLine(trimmed.substring(10));
            }
        }

        return result;
    }

    /**
     * Parse a line of space-separated coefficients
     */
    static parseCoeffLine(str) {
        const parts = str.trim().split(/\s+/);
        return parts.map(p => parseFloat(p) || 0);
    }

    /**
     * Combine (add) two sets of coefficients
     * @param {Object} existing - Existing {cSweep: {x,y,z}, bSweep: {x,y,z}}
     * @param {Object} newCoeffs - New coefficients to add
     * @returns {Object} Combined coefficients
     */
    static combineCoefficients(existing, newCoeffs) {
        const combine = (a, b) => {
            if (!a || !b) return b || a || [];
            const maxLen = Math.max(a.length, b.length);
            const result = [];
            for (let i = 0; i < maxLen; i++) {
                result[i] = (a[i] || 0) + (b[i] || 0);
            }
            return result;
        };

        return {
            cSweep: {
                x: combine(existing?.cSweep?.x, newCoeffs?.cSweep?.x),
                y: combine(existing?.cSweep?.y, newCoeffs?.cSweep?.y),
                z: combine(existing?.cSweep?.z, newCoeffs?.cSweep?.z)
            },
            bSweep: {
                x: combine(existing?.bSweep?.x, newCoeffs?.bSweep?.x),
                y: combine(existing?.bSweep?.y, newCoeffs?.bSweep?.y),
                z: combine(existing?.bSweep?.z, newCoeffs?.bSweep?.z)
            }
        };
    }

    /**
     * Generate M667 commands from structured coefficients object
     */
    static generateM667FromCoeffs(coeffs) {
        const lines = [];

        lines.push('; Rep5x Calibration Coefficients');
        lines.push('; Generated by Rep5x Calibrator');
        lines.push('');
        lines.push('; Enable calibration correction');
        lines.push('M667 S1');
        lines.push('');

        // C-sweep coefficients
        lines.push('; C-sweep coefficients');
        if (coeffs.cSweep.x) lines.push(`M667 A${this.formatCoeffs(coeffs.cSweep.x)}`);
        if (coeffs.cSweep.y) lines.push(`M667 B${this.formatCoeffs(coeffs.cSweep.y)}`);
        if (coeffs.cSweep.z) lines.push(`M667 C${this.formatCoeffs(coeffs.cSweep.z)}`);
        lines.push('');

        // B-sweep coefficients
        lines.push('; B-sweep coefficients');
        if (coeffs.bSweep.x) lines.push(`M667 D${this.formatCoeffs(coeffs.bSweep.x)}`);
        if (coeffs.bSweep.y) lines.push(`M667 E${this.formatCoeffs(coeffs.bSweep.y)}`);
        if (coeffs.bSweep.z) lines.push(`M667 F${this.formatCoeffs(coeffs.bSweep.z)}`);
        lines.push('');

        lines.push('M500');

        return lines.join('\n');
    }

    // Matrix helper functions
    static transpose(matrix) {
        if (matrix.length === 0) return [];
        const rows = matrix.length;
        const cols = matrix[0].length;
        const result = [];
        for (let j = 0; j < cols; j++) {
            result[j] = [];
            for (let i = 0; i < rows; i++) {
                result[j][i] = matrix[i][j];
            }
        }
        return result;
    }

    static matrixMultiply(A, B) {
        const rowsA = A.length;
        const colsA = A[0].length;
        const colsB = B[0].length;
        const result = [];

        for (let i = 0; i < rowsA; i++) {
            result[i] = [];
            for (let j = 0; j < colsB; j++) {
                let sum = 0;
                for (let k = 0; k < colsA; k++) {
                    sum += A[i][k] * B[k][j];
                }
                result[i][j] = sum;
            }
        }
        return result;
    }

    static matrixVectorMultiply(A, v) {
        const result = [];
        for (let i = 0; i < A.length; i++) {
            let sum = 0;
            for (let j = 0; j < A[i].length; j++) {
                sum += A[i][j] * v[j];
            }
            result[i] = sum;
        }
        return result;
    }

    static solveLinearSystem(A, b) {
        // Gaussian elimination with partial pivoting
        const n = A.length;

        // Create augmented matrix
        const aug = A.map((row, i) => [...row, b[i]]);

        // Forward elimination
        for (let col = 0; col < n; col++) {
            // Find pivot
            let maxRow = col;
            for (let row = col + 1; row < n; row++) {
                if (Math.abs(aug[row][col]) > Math.abs(aug[maxRow][col])) {
                    maxRow = row;
                }
            }

            // Swap rows
            [aug[col], aug[maxRow]] = [aug[maxRow], aug[col]];

            // Check for zero pivot
            if (Math.abs(aug[col][col]) < 1e-10) {
                continue;  // Skip this column (singular or nearly singular)
            }

            // Eliminate below
            for (let row = col + 1; row < n; row++) {
                const factor = aug[row][col] / aug[col][col];
                for (let j = col; j <= n; j++) {
                    aug[row][j] -= factor * aug[col][j];
                }
            }
        }

        // Back substitution
        const x = new Array(n).fill(0);
        for (let row = n - 1; row >= 0; row--) {
            let sum = aug[row][n];
            for (let col = row + 1; col < n; col++) {
                sum -= aug[row][col] * x[col];
            }
            if (Math.abs(aug[row][row]) > 1e-10) {
                x[row] = sum / aug[row][row];
            }
        }

        return x;
    }
}

// Export for module use
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { FourierFitter };
}
